language: node_js
script:
  - touch packages/bitbucket-codesandboxer/src/utils/github-auth.js
  - bolt
  - pnpm run build
  - pnpm run test
  - pnpm run flow
  - pnpm run lint
cache: pnpm
node_js:
  - 'node'
